### ISSUE TITLE
Things to work on

### ISSUE THREAD

**Issue by brennanaba** [SABS-R3-projects/Paint4Brains#29]
- Adjust intensity (slider)
- Region name and colour. Select region through name
- Manual preprocessing before segmentation (and after). And automatic beforehand
- Investigate preprocessing histogram normalisation.
- Add a progress bar when it is segmenting
- Add an undo button
- Hardware selection button needs more info.
- Estimate how long it would take to segment by bench marking machine.
- Reduce computational time
- Select brain slice with mouse wheel.
- Open software without brain
- Further scientific validation. (Freesurfer and manually labelled)
- Intercraneal volume normalization
- Calculate volumes for same patient within short timespan

**Comment by brennanaba** [comment]
Adjust intensity (slider)
Extraction slider.
Region name and colour. Select region through name - 
Manual preprocessing before segmentation (and after). _Itai_
Investigate preprocessing histogram normalisation - _Itai_
Add a progress bar when it is segmenting -
Hardware selection button needs more info. -
Estimate how long it would take to segment by bench marking machine. - 
Reduce computational time - _Andrei_ (Recreate QuickNAT in lite/tf 2.0 implementation)
Open software without brain
Further scientific validation. (Freesurfer and manually labelled)
Intercraneal volume normalization
Calculate volumes for same patient within short timespan
Write the grant request for David - _Andrei_

### **Now complete**
**Select brain slice with mouse wheel.**
**Add an undo button**
**Add a redo button**
**Automatic preprocessing before segmentation**

**Comment by brennanaba** [comment]
Adjust intensity (slider) 
Extraction slider. _Itai_
Manual preprocessing before segmentation (and after). _Itai_
Investigate preprocessing histogram normalisation - _Itai_
Add a progress bar when it is segmenting -
Hardware selection button needs more info. -
Estimate how long it would take to segment by bench marking machine. - 
Reduce computational time - _Andrei_ (Recreate QuickNAT in lite/tf 2.0 implementation)
Open software without brain (I don't like this)
Further scientific validation. (Freesurfer and manually labelled)
Intercraneal volume normalization
Calculate volumes for same patient within short timespan

### **Now complete**
**Region name and colour. Select region through name**
**Select brain slice with mouse wheel.**
**Add an undo button**
**Add a redo button**
**Automatic preprocessing before segmentation**
**Write the grant request for David**

**Comment by AndreiRoibu** [comment]
- Adjust intensity (slider)
- Extraction slider. Itai
- Add a progress bar when it is segmenting -
- Hardware selection button needs more info. -
- Estimate how long it would take to segment by bench marking machine. -
- Reduce computational time - Andrei (Recreate QuickNAT in lite/tf 2.0 implementation)
- Open software without brain (I don't like this)
- Further scientific validation. (Freesurfer and manually labelled)
- Intercraneal volume normalization
- Calculate volumes for same patient within short timespan
- Making different views views available when drawing different ROI - medium term task _(Show all views, maybe with one big main and 2 smaller secondaries at the sides, showing in real time what happens on the 2ndary planes what is being done on the main plane)_
- Have x,y,z on top showing slice number _(display coordinate, not the slice information - easy for making notes and keeping track of that - information of particular voxel you are hovering on; GE to check again if there are any bugs - confirmed it is there - maybe make it a bit clear)_
- Toolbar is not very intuitive - UX work? - might be worth asking _(when hovering over toolbar, show what everything does - maybe a balloon with some help information to make things clear)_

**### Now complete

- Region name and colour. Select region through name
- Select brain slice with mouse wheel.
- Add an undo button
- Add a redo button
- Automatic preprocessing before segmentation
- Manual preprocessing after segmentation. Itai - feature already present
- Write the grant request for David
- Manual preprocessing before segmentation
- Investigate preprocessing histogram normalisation - Itai**

**Comment by brennanaba** [comment]
Add a progress bar when it is segmenting -
Reduce computational time - Andrei (Recreate QuickNAT in lite/tf 2.0 implementation)
Further scientific validation. (Freesurfer and manually labelled)
Intercraneal volume normalization
Calculate volumes for same patient within short timespan - Can have a go at this - Andrei
Toolbar is not very intuitive - UX work? - might be worth asking (when hovering over toolbar, show what everything does - maybe a balloon with some help information to make things clear)

MRI Cron - another opensource brain software - have a library of atlases - might be cool for added functionality. Pre-loaded atlases might be a good functionality to allow people to compare atlas based vds non-atlas based stuff. ***

### **Now complete**

Region name and colour. Select region through name
Select brain slice with mouse wheel.
Add an undo button
Add a redo button
Automatic preprocessing before segmentation
Manual preprocessing after segmentation. Itai - feature already present
Write the grant request for David
Manual preprocessing before segmentation
Investigate preprocessing histogram normalisation - Itai*
Adjust intensity (slider)
Extraction slider. ItaHardware selection button needs more info. -
Estimate how long it would take to segment by bench marking machine. - Andrei - make note on times
Making different views views available when drawing different ROI - medium term task (Show all views, maybe with one big main and 2 smaller secondaries at the sides, showing in real time what happens on the 2ndary planes what is being done on the main plane)
Have x,y,z on top showing slice number (display coordinate, not the slice information - easy for making notes and keeping track of that - information of particular voxel you are hovering on; GE to check again if there are any bugs - confirmed it is there - maybe make it a bit clear)

**Comment by AndreiRoibu** [comment]
- Add a progress bar when it is segmenting -
- Further scientific validation. (Freesurfer and manually labelled)
- Intercraneal volume normalization
- Calculate volumes for same patient within short timespan - Can have a go at this - Andrei
- Toolbar is not very intuitive - UX work? - might be worth asking (when hovering over toolbar, show what everything does - maybe a balloon with some help information to make things clear)
- **NEW** Update docstrings and generate documentation
- **NEW** Look into paper submission

- MRI Cron - another opensource brain software - have a library of atlases - might be cool for added functionality. Pre-loaded atlases might be a good functionality to allow people to compare atlas based vds non-atlas based stuff. ***
- Reduce computational time - Andrei (Recreate QuickNAT in lite/tf 2.0 implementation)*** - time consuming, and other issues take priority

**Comment by AndreiRoibu** [comment]
Further scientific validation. (Freesurfer and manually labelled) - couldn't purchase original dataset - going for Hypothalamus one instead. 

Intercraneal volume normalization

Calculate volumes for same patient within short timespan - Can have a go at this - Andrei

Look into paper submission - Several journals with paper templates have been identified. 

Generate documentation - sphinx works but documentation generated isn't great. Might use it as starting point for manual at a later date. **** 

MRI Cron - another opensource brain software - have a library of atlases - might be cool for added functionality. Pre-loaded atlases might be a good functionality to allow people to compare atlas based vds non-atlas based stuff. ***

Reduce computational time - Andrei (Recreate QuickNAT in lite/tf 2.0 implementation)*** - time consuming, and other issues take priority

**Comment by brennanaba** [comment]
Outdated
